<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'cartorio', 'action' => 'emolumentos')); ?>" id="back-link">voltar</a>

<h1>Custas do Emolumento</h1>

<ul>
	<li>
		<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'cartorio','action' => 'cadastraremolumentovalor')); ?>" title="Cadastrar Emolumento">Cadastrar Valor do Emolumento</a>
	</li>
</ul>
 
<div id="messenger"><?php echo $this->flashMessenger();?></div>
