<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'cartorio', 'action' => 'tipodocumentos')); ?>" id="back-link">voltar</a>
 
<h1>Natureza dos Documentos</h1>

<ul>
	<li>
		<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'cartorio', 'action' => 'cadastrarnatureza')); ?>" title="Cadastrar natureza">Cadastrar Natureza</a>
	</li>
</ul>
 
<div id="messenger"><?php echo $this->flashMessenger();?></div>
 
<table class="display" id="tabela" >
    <thead>
        <tr>
            <th> # </th>
            <th>Nome</th>    
            <th></th>
        </tr>
     </thead>
     <tbody>
        <?php $i=0; foreach ( $this->naturezas as $natureza ) { $i=$i+1; ?>
            <tr>
                <td><?php echo $i; ?></td>
                <td><?php echo $this->escape($natureza->nome); ?></td>              
                <td align="center">
                    <a href="<?php echo $this->url(array(
                                       'module' => 'admin', 
									   'controller' => 'cartorio',
                                       'action'     => 'editarnatureza',
                                       'idNatureza'         => $this->escape($natureza->idNatureza))); ?>" title="Editar">Editar</a>
                    &nbsp;
                    <a href="<?php echo $this->url(array(
                                       'module' => 'admin', 
									   'controller' => 'cartorio',
                                       'action'     => 'deletarnatureza',
                                       'idNatureza'         => $this->escape($natureza->idNatureza))); ?>" title="Apagar">Apagar</a>
                </td>
            </tr>
        <?php } ?>        
     </tbody>
          
</table>
