<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'cartorio', 'action' => 'index'), null, true); ?>" id="back-link">voltar</a>

<h1>Lotes de Selos</h1>
<hr />
<div id="messenger"><?php echo $this->flashMessenger();?></div>
<ul>
<li><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'cartorio', 'action' => 'cadastrarselo'), null, true); ?>" title="Cadastrar Feriado">Cadastrar Selo</a></li>
 </ul>
<table cellspacing="1" cellpadding="1" border="1" class="display" id="tabela"  >
    <thead>
        <tr>
            <th> # </th>
            <th>Tipo</th>
			<th>Série</th>
			<th>Nº Inicial</th>
			<th>Nº Final</th>
			<th>Nota Fiscal</th>
			<th>Data da Nota</th>
			<th>Data da Inclusão</th>           
            <th></th>
        </tr>
     </thead>
     <tbody>
        <?php $i=0; foreach ( $this->selos as $selo ) { $i=$i+1; ?>
            <tr>
                <td align="center"><?php echo $i; ?></td>
                <td align="center"><?php echo $this->escape($selo->tipo); ?></td>
				<td align="center"><?php echo $this->escape($selo->serie); ?></td>
				<td align="center"><?php echo $this->escape($selo->numeroinicial); ?></td> 
				<td align="center"><?php echo $this->escape($selo->numerofinal); ?></td> 
				<td align="center"><?php echo $this->escape($selo->notafiscal); ?></td> 
				<td align="center"><?php echo $this->date($this->escape($selo->data_nota)); ?></td>
				<td align="center"><?php echo $this->escape($selo->data_inclusao); ?></td>                
                <td align="center">
                    <a href="<?php echo $this->url(array(
                                       'module' => 'admin',
                                       'controller' => 'cartorio',
                                       'action'     => 'editarselo',
                                       'idSelos'         => $this->escape($selo->idSelos))); ?>" title="Editar">Editar</a>
                    &nbsp;
                    <a href="<?php echo $this->url(array(
                                       'module' => 'admin',
                                       'controller' => 'cartorio',
                                       'action'     => 'deletarselo',
                                       'idSelos'         => $this->escape($selo->idSelos))); ?>" title="Apagar">Apagar</a>
                </td>
            </tr>
        <?php } ?>        
     </tbody>
     
</table>
