<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'cartorio', 'action' => 'index')); ?>" id="back-link">voltar</a>

<h1>Tipos de Documentos</h1>

<ul>
	<li>
		<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'cartorio','action' => 'cadastrartipodocumentos')); ?>" title="Cadastrar Tipo de Documento">Cadastrar Tipo de Documento</a>
	</li>
	<li>
		<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'cartorio', 'action' => 'natureza')); ?>" title="Natureza">Natureza</a>
	</li>
	
	
</ul>

<div id="messenger"><?php echo $this->flashMessenger();?></div>

<table cellspacing="1" cellpadding="1" border="1" class="display" id="tabela" >
    <thead>
        <tr>
            <th> # </th>
            <th>Tipo de Documento</th>
            <th>Documento Sem Valor</th>
			<th>Natureza</th>
			<th></th>
		</tr>
     </thead>
     <tbody>
        <?php $i=0; foreach ( $this->tipodocumentos as $tipodocumento ) { $i=$i+1; ?>
            <tr>
                <td><?php echo $i; ?></td>
                <td><?php echo $this->escape($tipodocumento->nome); ?></td>
				<td  align="center"><?php 	if($tipodocumento->valor == '1') echo 'Sim';
							else echo 'Não'?></td>
				<td align="center"><?php echo $this->escape($tipodocumento->natu); ?></td> 
                <td align="center">
                    <a href="<?php echo $this->url(array(
                                       'module' => 'admin', 
									   'controller' => 'cartorio',
                                       'action'     => 'editartipodocumentos',
                                       'idTipodocumentos'         => $this->escape($tipodocumento->idTipodocumentos))); ?>" title="Editar">Editar</a>
                    &nbsp;
                    <a href="<?php echo $this->url(array(
                                       'module' => 'admin', 
									   'controller' => 'cartorio',
                                       'action'     => 'deletartipodocumentos',
                                       'idTipodocumentos'         => $this->escape($tipodocumento->idTipodocumentos))); ?>" title="Apagar">Apagar</a>
                </td>
            </tr>
        <?php } ?>        
     </tbody>
          
</table>
