<a href="<?php echo $this->url(array('module' => 'registro', 'controller' => 'index', 'action' => 'index'), null, true); ?>" id="back-link">voltar</a>

<h1>Cadastro de Títulos e documentos</h1>
<hr />
<div id="messenger"><?php echo $this->flashMessenger();?></div>

<ul id="menu-grid">
	<li>
		<a href="<?php echo $this->url(array('module' => 'registro', 'controller' => 'titulodocumentos','action' => 'pedido')); ?>" title="Cadastro de Títulos e Documentos.">
			<img src="<?php echo $this->baseUrl(); ?>/css/icons/blank.png" />
			<br/>
			Cadastro de Pedidos
		</a>
	</li>
	<li>
		<a href="<?php echo $this->url(array('module' => 'registro', 'controller' => 'titulodocumentos','action' => 'cadastrotitulodocumento')); ?>" title="Cadastro de Títulos e Documentos.">
			<img src="<?php echo $this->baseUrl(); ?>/css/icons/blank.png" />
			<br/>
			Cadastro de Títulos e Documentos
		</a>
	</li>
	<li>
		<a href="<?php echo $this->url(array('module' => 'registro', 'controller' => 'titulodocumentos', 'action' => 'acompanhamento')); ?>" title="Cadastro de Títulos e Documentos.">
			<img src="<?php echo $this->baseUrl(); ?>/css/icons/blank.png" />
			<br/>
			Acompanhamento de Pedidos
		</a>
	</li>
	
	<hr class="clear"/>
</ul>