<a href="<?php echo $this->url(array('module' => 'registro', 'controller' => 'titulodocumentos', 'action' => 'acompanhamento'), null, true); ?>" id="back-link">voltar</a>

<h1>Cadastro de Pedido </h1>

<div id="messenger"><?php echo $this->flashMessenger();?></div>

<?php echo $this->form;
		
echo $this->formP;
?>

<table cellspacing="1" cellpadding="1" border="1" class="display" id="tabela"  >
    <thead>
        <tr>
            <th>#</th>
            <th>Documento</th>
			<th>Nome</th>
            <th>Ação</th>
        </tr>
    </thead>
    <tbody>
<?php
	if(isset($_SESSION['pessoascitadas'])){
		$i = 1;
		foreach ($_SESSION['pessoascitadas'] as $pessoa) {
?> 
        <tr>
            <td align="center"><?php echo $i; ?></td>
            <td align="center"><?php echo $this->documento($pessoa['numeroidentificacao'], $pessoa['tipo_identificacao']);?></td>
			<td align="center"><?php echo $this->escape($pessoa['nome']); ?></td>
            <td align="center" title="Clique para modificar o status da Pessoa." class="slide"><b><?php echo $this->escape($pessoa['notificar']); ?></b>
				<div class="edit">
					<a title="Clique para remover a Pessoa."href="<?php echo $this->url(array('module' => 'registro', 'controller' => 'titulodocumentos', 'action' => 'removerpessoascitadas', 'remove' => ($i-1)), null, true); ?>" id="editarpessoascitadas">Remover Pessoa</a><br>
					<a title="Clique para tornar esta Pessoa apenas Citada."href="<?php echo $this->url(array('module' => 'registro', 'controller' => 'titulodocumentos', 'action' => 'changepessoacitada', 'id' => ($i-1)), null, true); ?>" id="changepessoacitada">Pessoa Citada	</a><br>
					<a title="Clique para tornar esta Pessoa em Notificante."href="<?php echo $this->url(array('module' => 'registro', 'controller' => 'titulodocumentos', 'action' => 'changenotificante', 'id' => ($i-1)), null, true); ?>" id="changenotificante">Notificante</a><br>
					<a title="Clique para tornar esta Pessoa em Notificada"href="<?php echo $this->url(array('module' => 'registro', 'controller' => 'titulodocumentos', 'action' => 'changenotificado', 'id' => ($i-1)), null, true); ?>" id="changenotificado">Notificado</a><br>
					<a title="Clique para tornar esta Pessoa em Apresentante"href="<?php echo $this->url(array('module' => 'registro', 'controller' => 'titulodocumentos', 'action' => 'changeapresentante', 'id' => ($i-1)), null, true); ?>" id="changeapresentante">Apresentante</a><br>
				</div>
			</td>
        </tr> 
<?php
			$i++;
		}
	}
?> 		
    </tbody>
				
</table>


<style>
input{
	text-transform: uppercase;
} 
</style>

<script type="text/javascript">


	$(function() {
		
		$('.slide').click(function() {
		
			if ($('.edit').is(":hidden")) {
				$(".edit").slideDown("slow");
			} else {
				$(".edit").slideUp("slow");
			}
		});
		
		var taxajudiciaria, funcivil, averbacao, averbacaopgextra, notificacao, notificacaopgextra, notificacaopgextra, soma;
		

		var tipoemolumento = $("#tipoemolumento").val();
		var valor = $("#valordocumento").val();

		$.ajax({
			url:"<?php echo $this->url(array('module' => 'registro', 'controller' => 'titulodocumentos', 'action' => 'calculocusta'), null, true); ?>",
			dataType:'json',
			encoding: 'utf-8',
			data:{id: tipoemolumento, valor: valor},
			type:'GET',
			success: function(data){						

				if(data.tipo_custa == 0)
				{
					var totalcustas = new Number(0);
					
					if($('#numeropaginas').val() > data.pagina_inicial)
					{
						var qtpagina = $('#numeropaginas').val() - data.pagina_inicial;
						totalcustas = totalcustas + ($('#numerovias').val() * (qtpagina * data.pagina_extra));
						totalcustas = totalcustas + ($('#numerovias').val() * data.emolumento);
					}
					else{
						totalcustas = totalcustas + ($('#numerovias').val() * data.emolumento);
					}
					var valor_correio = parseFloat(($('#valor_correio').val()).replace(/[$,]+/g,""));
					var outrasdespesas = parseFloat(($('#outrasdespesas').val()).replace(/[$,]+/g,""));
					
					funcivil =  parseInt((data.funcivil).replace(/[$.]+/g,""));
					taxa = parseInt((data.taxa).replace(/[$.]+/g,""));										
					
					totalcustas = totalcustas + (valor_correio + outrasdespesas + (funcivil + taxa));
					parseFloat(totalcustas);
					totalcustas = totalcustas *100;
					totalcustas = Math.floor(totalcustas);
					totalcustas = totalcustas / 100;
						
					$('#emolumento').val(data.emolumento);
					$('#emolumento').setMask('decimal');
					$('#total_custas').val(totalcustas);
					$('#total_custas').setMask('decimal');
					$('#taxajudiciaria').val(data.taxa);
					$('#taxajudiciaria').setMask('decimal');
					$('#funcivil').val(data.funcivil);
					$('#funcivil').setMask('decimal');
					
					totalcustasDec = ((totalcustas + (data.funcivil + data.taxa)) / 100);
					emolumentoDec = (data.emolumento / 100);
					taxajudiciariaDec = (data.taxa / 100);
					funcivilDec = (data.funcivil / 100);
						
				}
				else if(data.tipo_custa == 1)
				{
					var custas = data.soma;
					var totalcustas = new Number();
					var outrasdespesas = parseFloat(($('#outrasdespesas').val()).replace(/[$,]+/g,"."));
					var valor_correio = parseFloat(($('#valor_correio').val()).replace(/[$,]+/g,"."));
					var numerovias = parseInt($('#numerovias').val());
					
					custas = parseFloat(custas);
					emolumentos = parseFloat(data.emolumento);
					mult = parseFloat(numerovias * (emolumentos));
					
					totalcustas = custas + emolumentos +  mult + outrasdespesas + valor_correio;
					totalcustas = totalcustas *100;
					totalcustas = Math.floor(totalcustas);
					totalcustas = totalcustas / 100;


					
					$('#emolumento').val(data.emolumento);
					$('#emolumento').setMask('decimal');
					$('#total_custas').val(totalcustas);
					$('#total_custas').setMask('decimal');
					$('#taxajudiciaria').val(data.taxa);
					$('#taxajudiciaria').setMask('decimal');
					$('#funcivil').val(data.funcivil);
					$('#funcivil').setMask('decimal');
				}
			}
		});

		
		$('#Pessoa-estado_citado').change(function() { 
		
	    	var id = $(this).val();		    	    			     

	    	$.ajax({
	    		url:"<?php echo $this->url(array('module' => 'registro', 'controller' => 'titulodocumentos', 'action' => 'getcidades'), null, true); ?>",
    			dataType:'html',
    			encoding: 'utf-8',
   				data:{id: id},
    			type:'GET',
    			success: function(data){
            				$('#Pessoa-cidade_citado').html(data);
    			}
			});
		});
		
		$('#Pessoa-documento_citado').change(function() { 
			
	    	var doc = $(this).val();
			var i = doc.replace(/[^0-9]/g, "");
	    		
	    	$.ajax({
	    		url:"<?php echo $this->url(array('module' => 'registro', 'controller' => 'titulodocumentos' , 'action' => 'getpessoa'), null, true); ?>",
    			dataType:'html',
    			//encoding: 'iso-8859-1',
   				data:{doc: doc},
    			type:'GET',
    			onFailure: function() {
                    	    alert("Falha na execução desta tarefa.");
                },
    			success: function(data){
                	$('#Pessoa-nome_citado').html(data);
                	$("#Pessoa-nome_citado").val($('#idnome'+i).val()) ;
                	$("#Pessoa-telefone_citado").val($('#idtelefone'+i).val());
					$("#Pessoa-cep_citado").val($('#idcep'+i).val());
                	$("#Pessoa-endereco_citado").val($('#idendereco'+i).val());
                	$("#Pessoa-complemento_citado").val($('#idcomplemento'+i).val());
                	$("#Pessoa-bairro_citado").val($('#idbairro'+i).val());
                	$("#Pessoa-numero_citado").val($('#idnumero'+i).val());
					$("#Pessoa-obs_citado").val($('#idobs'+i).val());
					var uf = $('#iduf'+i).val();
                	$("#Pessoa-estado_citado").val(uf);
        	    	$.ajax({
        	    		url:"<?php echo $this->url(array('module' => 'registro', 'controller' => 'titulodocumentos', 'action' => 'getcidades'), null, true); ?>",
            			dataType:'html',
            			encoding: 'utf-8',
           				data:{id: uf},
            			type:'GET',
            			success: function(data){
                    				$('#Pessoa-cidade_citado').html(data);
            					 }
        			});
    			}
			});
		});

	});
</script>