<a href="<?php echo $this->url(array('module' => 'registro', 'controller' => 'titulodocumentos', 'action' => 'index'), null, true); ?>" id="back-link">voltar</a>

<h1>Cadastro de Pedido </h1>

<div id="messenger"><?php echo $this->flashMessenger();?></div>

<?php 	
		echo $this->form;
		echo $this->requerente;
		echo $this->itempedido;
		echo $this->notificante;

?>
<hr class="clear" /><br/>
<hr />
<table cellspacing="1" cellpadding="1" border="1" class="display" id="tabela"  >
    <thead>
        <tr>
            <th>Item pedido</th>
            <th>Tipo do Documento</th>
			<th>Situação</th>
            <th>Total das Custas</th>
        </tr>
    </thead>
    <tbody>
<?php
	if(isset($_SESSION['itempedido'])){
		foreach ($_SESSION['itempedido'] as $item) {
?> 
        <tr>
            <td><?php echo $this->escape($item['datasituacao']); ?></td>
            <td><?php echo $this->escape($item['tipodocumentos']); ?></td>
			<td><?php echo $this->escape($item['pedido_situacao']); ?></td>
            <td><?php echo $this->escape($item['valordocumento']); ?></td>
        </tr> 
<?php
		}
	}
?> 		
    </tbody>

</table>



<style>
input{
	text-transform: uppercase;
} 
</style>

<script type="text/javascript">


	$(function() {
		var taxajudiciaria, funcivil, averbacao, averbacaopgextra, notificacao, notificacaopgextra, notificacaopgextra, soma;

		var tabs = $('#form-tab');
		var legends = $(tabs).find('fieldset').get();

		var titles = $('<ul></ul>');
		$.each(legends, function(index, value) { 
			var legend = $(value).find('legend');

			var id = $(value).attr('id');
			var a = $('<a></a>').attr('href', '#' + id).text($(legend).text());
			var li = $('<li></li>').append(a);

			$(legend).remove();

			$(titles).append(li);			
			var div = $('<div></div>').attr('id', id);
			$(div).html($(value).html());
			$(tabs).append(div);

			$(value).remove();
		});
		$(tabs).prepend(titles);
		$(tabs).tabs();
		
		$('input').change(function(){
			var tipoemolumento = $("#itempedido-tipoemolumento").val();
			var valor = $("#itempedido-valordocumento").val();
			
			$.ajax({
	    		url:"<?php echo $this->url(array('module' => 'registro', 'controller' => 'titulodocumentos', 'action' => 'calculocusta'), null, true); ?>",
    			dataType:'json',
    			encoding: 'utf-8',
   				data:{id: tipoemolumento, valor: valor},
    			type:'GET',
    			success: function(data){						
					var valordocumento = parseInt(valor);
						
					if(data.tipo_custa == 0)
					{
						var totalcustas = 0
							
						if($('#itempedido-numeropaginas').val() > data.pagina_inicial)
						{
							var qtpagina = $('#itempedido-numeropaginas').val() - data.pagina_inicial;
							totalcustas = totalcustas + ($('#itempedido-numerovias').val() * (qtpagina * data.pagina_extra));
							totalcustas = totalcustas + ($('#itempedido-numerovias').val() * data.emolumento);
						}
						else{
							totalcustas = totalcustas + ($('#itempedido-numerovias').val() * data.emolumento);
						}
						totalcustas = (totalcustas + (data.funcivil + data.taxa));
									
						$('#itempedido-emolumento').val(data.emolumento);
						$('#itempedido-emolumento').setMask('decimal');
						$('#itempedido-total_custas').val(totalcustas);
						$('#itempedido-total_custas').setMask('decimal');
						$('#itempedido-taxajudiciaria').val(data.taxa);
						$('#itempedido-taxajudiciaria').setMask('decimal');
						$('#itempedido-funcivil').val(data.funcivil);
						$('#itempedido-funcivil').setMask('decimal');
									
						totalcustasDec = ((totalcustas + (data.funcivil + data.taxa)) / 100);
						emolumentoDec = (data.emolumento / 100);
						taxajudiciariaDec = (data.taxa / 100);
						funcivilDec = (data.funcivil / 100);
					}
    			}
			});
		});

		$('#Requerente-estado_requerente').change(function() { 

	    	var id = $(this).val();		    	    			     

	    	$.ajax({
	    		url:"<?php echo $this->url(array('module' => 'registro', 'controller' => 'titulodocumentos', 'action' => 'getcidades'), null, true); ?>",
    			dataType:'html',
    			encoding: 'utf-8',
   				data:{id: id},
    			type:'GET',
    			success: function(data){
            				$('#Requerente-cidade_requerente').html(data);
    			}
			});
		});

		$('#itempedido-estado_notificante').change(function() { 

	    	var id = $(this).val();		    	    			     

	    	$.ajax({
	    		url:"<?php echo $this->url(array('module' => 'registro', 'controller' => 'titulodocumentos', 'action' => 'getcidades'), null, true); ?>",
    			dataType:'html',
    			encoding: 'utf-8',
   				data:{id: id},
    			type:'GET',
    			success: function(data){
            				$('#cidade_notificante').html(data);
    			}
			});
		});
		
		$('#Requerente-documento_requerente').change(function() { 

	    	var doc = $(this).val();
			var i = doc.replace(/[^0-9]/g, "");

	    	$.ajax({
	    		url:"<?php echo $this->url(array('module' => 'registro', 'controller' => 'titulodocumentos' , 'action' => 'getpessoa'), null, true); ?>",
    			dataType:'html',
    			//encoding: 'iso-8859-1',
   				data:{doc: doc},
    			type:'GET',
    			onFailure: function() {
                    	    alert("Falha na execução desta tarefa.");
                },
    			success: function(data){
                	$('#Requerente-nome_requerente').html(data);
                	$("#Requerente-nome_requerente").val($('#idnome'+i).val()) ;
                	$("#Requerente-telefone_requerente").val($('#idtelefone'+i).val());
					$("#Requerente-cep_requerente").val($('#idcep'+i).val());
                	$("#Requerente-endereco_requerente").val($('#idendereco'+i).val());
                	$("#Requerente-complemento_requerente").val($('#idcomplemento'+i).val());
                	$("#Requerente-bairro_requerente").val($('#idbairro'+i).val());
                	$("#Requerente-numero_requerente").val($('#idnumero'+i).val());
					$("#Requerente-obs_requerente").val($('#idobs'+i).val());
					var uf = $('#iduf'+i).val();
                	$("#Requerente-estado_requerente").val(uf);
        	    	$.ajax({
        	    		url:"<?php echo $this->url(array('module' => 'registro', 'controller' => 'titulodocumentos', 'action' => 'getcidades'), null, true); ?>",
            			dataType:'html',
            			encoding: 'utf-8',
           				data:{id: uf},
            			type:'GET',
            			success: function(data){
                    				$('#Requerente-cidade_requerente').html(data);
            					 }
        			});
    			}
			});
		});
		
		$('#itempedido-notificante-documento_notificante').change(function() { 

	    	var doc = $(this).val();
			var i = doc.replace(/[^0-9]/g, "");

	    	$.ajax({
	    		url:"<?php echo $this->url(array('module' => 'registro', 'controller' => 'titulodocumentos' , 'action' => 'getpessoa'), null, true); ?>",
    			dataType:'html',
    			//encoding: 'iso-8859-1',
   				data:{doc: doc},
    			type:'GET',
    			onFailure: function() {
                    	    alert("Falha na execução desta tarefa.");
                },
    			success: function(data){
                	$('#itempedido-notificante-documento_notificante').html(data);
                	$("#itempedido-notificante-nome_notificante").val($('#idnome'+i).val()) ;
                	$("#itempedido-notificante-telefone_notificante").val($('#idtelefone'+i).val());
					$("#itempedido-notificante-cep_notificante").val($('#idcep'+i).val());
                	$("#itempedido-notificante-endereco_notificante").val($('#idendereco'+i).val());
                	$("#itempedido-notificante-complemento_notificante").val($('#idcomplemento'+i).val());
                	$("#itempedido-notificante-bairro_notificante").val($('#idbairro'+i).val());
                	$("#itempedido-notificante-numero_notificante").val($('#idnumero'+i).val());
					$("#itempedido-notificante-obs_notificante").val($('#idobs'+i).val());
					var uf = $('#iduf'+i).val();
                	$("#itempedido-notificante-estado_notificante").val(uf);
        	    	$.ajax({
        	    		url:"<?php echo $this->url(array('module' => 'registro', 'controller' => 'titulodocumentos', 'action' => 'getcidades'), null, true); ?>",
            			dataType:'html',
            			encoding: 'utf-8',
           				data:{id: uf},
            			type:'GET',
            			success: function(data){
                    				$('#itempedido-notificante-cidade_notificante').html(data);
            					 }
        			});
    			}
			});
		});

		$('#itempedido-notificado-documento_notificado').change(function() { 

	    	var doc = $(this).val();
			var i = doc.replace(/[^0-9]/g, "");

	    	$.ajax({
	    		url:"<?php echo $this->url(array('module' => 'registro', 'controller' => 'titulodocumentos' , 'action' => 'getpessoa'), null, true); ?>",
    			dataType:'html',
    			//encoding: 'iso-8859-1',
   				data:{doc: doc},
    			type:'GET',
    			onFailure: function() {
                    	    alert("Falha na execução desta tarefa.");
                },
    			success: function(data){
                	$('#itempedido-notificado-documento_notificado').html(data);
                	$("#itempedido-notificado-nome_notificado").val($('#idnome'+i).val()) ;
                	$("#itempedido-notificado-telefone_notificado").val($('#idtelefone'+i).val());
					$("#itempedido-notificado-cep_notificado").val($('#idcep'+i).val());
                	$("#itempedido-notificado-endereco_notificado").val($('#idendereco'+i).val());
                	$("#itempedido-notificado-complemento_notificado").val($('#idcomplemento'+i).val());
                	$("#itempedido-notificado-bairro_notificado").val($('#idbairro'+i).val());
                	$("#itempedido-notificado-numero_notificado").val($('#idnumero'+i).val());
					$("#itempedido-notificado-obs_notificado").val($('#idobs'+i).val());
					var uf = $('#iduf'+i).val();
                	$("#itempedido-notificado-estado_notificado").val(uf);
        	    	$.ajax({
        	    		url:"<?php echo $this->url(array('module' => 'registro', 'controller' => 'titulodocumentos', 'action' => 'getcidades'), null, true); ?>",
            			dataType:'html',
            			encoding: 'utf-8',
           				data:{id: uf},
            			type:'GET',
            			success: function(data){
                    				$('#itempedido-notificado-cidade_notificado').html(data);
            					 }
        			});
    			}
			});
		});
	});
	
</script>