<div id="messenger"><?php echo $this->flashMessenger();?></div>
<ul id="menu-grid">
	<li>
		<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'usuario','action' => 'index')); ?>" title="Usuários, grupos e permissões.">
			<img src="<?php echo $this->baseUrl(); ?>/css/icons/seguranca.png" />
			<br/>
			Segurança
		</a>
	</li>
	<li>
		<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'cartorio', 'action' => 'index')); ?>" title="Administração dos dados sobre o Cartório e outros.">
			<img src="<?php echo $this->baseUrl(); ?>/css/icons/administracao.png" />
			<br/>
			Administração
		</a>
	</li>
	<hr class="clear"/>
</ul>